fix: patch cluster status
unbxd/lucene-solr pull request #17
Opened 2021-08-06 08:59 UTC by apoorvprecisely

2021-08-06 10:20 UTC, keshareenv commented
> _No description provided._

is this a complete port of https://issues.apache.org/jira/browse/SOLR-10720, i see some changes to `OverseerCollectionMessageHandler` as well in that patch

2021-08-06 10:32 UTC, apoorvprecisely commented
adding it, paths have changed

2021-08-09 10:16 UTC, keshareenv approved these changes
lgtm, please add git secrets before merging

2021-08-09 10:17 UTC, keshareenv requested changes

2021-08-09 10:17 UTC, keshareenv commented on .github/workflows/build.yaml
> +          BUILD_TAG: ${{ steps.extract_tag.outputs.BUILD_TAG }}
step extract_tag missing

2021-08-11 05:59 UTC, uknth commented
Split this code in 2 PRs. 
1. Migration from Travis to Github Actions
2. Code Change with Test Cases

2021-08-11 05:59 UTC, closed without merging